### ISSUE TITLE
Setting environment variables

### ISSUE THREAD

**Issue by ramden** [michaelleeallen/jest-junit-reporter#9]
How and where would one set the environment variables to customize the path and filename?

This would be a great addition in the readme

**Comment by andybflynn** [comment]
You can try setting the environment variables in your NPM script, e.g.
```
...
"scripts": {
  "test": "TEST_REPORT_FILENAME='custom-report-name.xml' jest"
}
...
```

Then when you run `npm test` it'll name the report custom-report-name.xml

**Comment by michaelleeallen** [comment]
Thank you, @andybflynn for providing an answer here.

@ramden if you are using a CI servcer you can also set environment properties. Here are a few references:
https://circleci.com/docs/2.0/env-vars/
https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/
https://docs.travis-ci.com/user/environment-variables

**Comment by michaelleeallen** [comment]
See my last comment for solution.

**Comment by cope** [comment]
> You can try setting the environment variables in your NPM script, e.g.
> ```
> ...
> "scripts": {
>   "test": "TEST_REPORT_FILENAME='custom-report-name.xml' jest"
> }
> ...
> ```
> Then when you run `npm test` it'll name the report custom-report-name.xml

On Windows I need to prefix with `cross-env TEST_REPORT_PATH=coverage`, but frankly, I find this to be a crappy solution. Having `jest-unit-reporter` attribute in package.json would be a lot better and cleaner IMHO.
